name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: ubuntu-18.04
            # Enable warnings (;--warnings-as-errors=*)
            extra-cmake-arguments : >-
              -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
              -D CMAKE_CXX_CLANG_TIDY="/usr/bin/clang-tidy"
          - os: windows-latest
            # Enable warnings and exclude third-party headers for them
            extra-cmake-arguments: >-
              -D CMAKE_CXX_FLAGS="/experimental:external /external:I $env:VCPKG_ROOT/installed/$env:RUNVCPKG_VCPKG_TRIPLET/include /external:W0 /external:templates- /W4 /wd4530 /WX"
              -D VCPKG_TARGET_TRIPLET=$env:RUNVCPKG_VCPKG_TRIPLET
              -D CMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
    steps:
    - name: Enable Git symlinks
      if: runner.os == 'Windows'
      run: git config --global core.symlinks true

    - name: Clone repo
      uses: actions/checkout@v2.3.3

    - name: Install apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev clang-tidy

    #  To find versions from vcpkg
    - name: Install PkgConfig
      if: runner.os == 'Windows'
      run: choco install pkgconfiglite

    - name: Install vcpkg packages
      uses: lukka/run-vcpkg@v4.1
      if: runner.os == 'Windows'
      with:
        vcpkgArguments: tesseract ecm qt5-base qt5-svg qt5-multimedia qt5-winextras qt5-tools --triplet x64-windows
        vcpkgGitCommitId: 56fffbe49dfb4dd8fae0940f272c5fd2b86be991
      env:
        VCPKG_DISABLE_METRICS: 1

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -D WITH_PORTABLE_MODE=ON ${{ matrix.extra-cmake-arguments }}
        cmake --build . --parallel 2
