name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: ubuntu-18.04
            extra-cmake-arguments : >-
              -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
              -D CMAKE_CXX_CLANG_TIDY="clang-tidy;--warnings-as-errors=*"
          - os: windows-latest
            # Enable warnings and exclude third-party headers for them
            extra-cmake-arguments: >-
              -D CMAKE_CXX_FLAGS="/experimental:external /external:anglebrackets /external:W0 /W4 /wd4530 /WX"
              -D VCPKG_TARGET_TRIPLET=$env:RUNVCPKG_VCPKG_TRIPLET
              -D CMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.3.3

    - name: Install apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev clang-tidy

    #  To find versions from vcpkg
    - name: Install PkgConfig
      if: runner.os == 'Windows'
      run: choco install pkgconfiglite

    - name: Install vcpkg packages
      uses: lukka/run-vcpkg@v6.0
      if: runner.os == 'Windows'
      with:
        vcpkgArguments: tesseract[cpu-independed] ecm qt5-base qt5-svg qt5-multimedia qt5-winextras qt5-tools --triplet x64-windows
        vcpkgGitCommitId: 066c6fd712a3b7015388de644e44faf9774f3641
      env:
        VCPKG_DISABLE_METRICS: 1

    - name: Build
      run: |
        cmake -B build -D WITH_PORTABLE_MODE=ON ${{ matrix.extra-cmake-arguments }}
        cmake --build build --parallel 2
