name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: ubuntu-18.04
            CXXFLAGS: '-Wall -Wextra -pedantic -Werror'
          - os: windows-latest
            extra-cmake-arguments: '-D VCPKG_TARGET_TRIPLET=x64-windows -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'
            CXXFLAGS: '/W4' #TODO: Use /WX
    steps:
    - name: Enable Git symlinks
      if: runner.os == 'Windows'
      run: git config --global core.symlinks true

    - name: Clone repo
      uses: actions/checkout@v2.3.1
      with:
        submodules: true

    - name: Install apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev

    - name: Install Qt
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v2.7.2

    - name: Cache vcpkg packages
      uses: actions/cache@v2
      if: runner.os == 'Windows'
      with:
        path: C:/vcpkg/packages
        key: ${{ matrix.os }}-ecm-tesseract41

    - name: Install vcpkg packages
      if: runner.os == 'Windows'
      run: vcpkg install tesseract ecm --triplet x64-windows

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -D PORTABLE_MODE=ON -D WITH_OCR=ON ${{ matrix.extra-cmake-arguments }}
        cmake --build . --parallel 2
      env:
        CXXFLAGS: ${{ matrix.CXXFLAGS }}
