name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    env:
      ECM_ROOT: 'C:\Program Files\ECM'
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: ubuntu-18.04
            CXXFLAGS: '-Wall -Wextra -pedantic -Werror'
          - os: windows-latest
            CMAKE_TOOLCHAIN_FILE: 'C:\vcpkg\scripts\buildsystems\vcpkg.cmake'
            extra-cmake-modules: '5.70.0'
            CXXFLAGS: '/W4 /WX'
    steps:
    - name: Enable Git symlinks
      if: runner.os == 'Windows'
      run: git config --global core.symlinks true

    - name: Clone repo
      uses: actions/checkout@v2.3.1
      with:
        submodules: true

    - name: Install dependent apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev

    - name: Install Qt
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v2.7.2

    - name: Install Extra CMake Modules
      if: runner.os == 'Windows'
      run: |
        git clone --depth 1 --branch v${{ matrix.extra-cmake-modules }} https://github.com/KDE/extra-cmake-modules.git
        cmake -S extra-cmake-modules -B extra-cmake-modules/build
        cmake --build extra-cmake-modules/build --target install

    - name: Install Tesseract
      if: runner.os == 'Windows'
      run: vcpkg install tesseract:x64-windows-md

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -D PORTABLE_MODE=ON -D WITH_OCR=ON -D CMAKE_TOOLCHAIN_FILE=${{ matrix.CMAKE_TOOLCHAIN_FILE }}
        cmake --build . --parallel 2
      # env:
      #   CXXFLAGS: ${{ matrix.CXXFLAGS }}

